---
title: "CosMx CRC dataset - Analysis"
author: "Samuel Gunz"
date:  last-modified
format: 
    html:
      toc: true
      self-contained: true
      highlight-style: github
      code-line-numbers: true
output-dir: "../docs/"
---
# Setup

```{r}
#| message: false
#| echo: false
library("SpatialExperiment")
library("sosta")
library("ggplot2")
library("tidyr")
library("dplyr")
library("sf")
library("smoothr")
library("spdep")
library("ggspavis")
library("mumosa")
library("BiocParallel")
library("scater")
bpparam <- MulticoreParam(6)

theme_set(theme_bw())
```

Set up for plotting

```{r}
# Specific color mapping - source: https://github.com/HelenaLC/WTx-TVA/blob/d75d0cd20a9880f11c1368e37ba39660e3f2e82c/code/_utils.R#L4
# custom order
.fw <- facet_wrap(~factor(typ, c("110_REF", "110_TVA1", "110_TVA2",
                                 "110_TVA3", "110_CRC")))
.pal_sub <- c(epi="gold2", imm="cyan2", str="magenta2")

```

```{r}
# Specific color mapping - source: https://github.com/HelenaLC/WTx-TVA/blob/d75d0cd20a9880f11c1368e37ba39660e3f2e82c/code/_utils.R#L4
typCols <- c(
  "110_REF" = "seagreen",
  "110_TVA1" = "dodgerblue",
  "110_TVA2" = "royalblue",
  "110_TVA3" = "slateblue",
  "110_CRC" = "tomato"
)
```

Read in data

```{r}
spe <- readRDS("~/data_no_backup/CosMx_TVA/110.rds")
spe <- toSpatialExperiment(spe, spatialCoordsNames = c("CenterX_global_px", "CenterY_global_px"))
# for later reconstruction
spe$foo <- "foo"
```


```{r}
# selected fov of interest
ls <- c(105, 106, 107, 108, 109, 110, 111,
        133, 134, 135, 136, 137, 138, 139,
        96, 97, 98,
        #25, 
        26,
        27, 28, 29, 30,
        #382, 383, 384,
        46, 47, 48, 49,
        50, 51, 
        #52,
        59, 60, 61, 62, 63, 64, 65,
        92, 93, 94, 95)

gc()
```


```{r}
#| fig-width: 5
#| fig-height: 9

cbind(spatialCoords(spe), colData(spe)) |>
  as.data.frame() |> 
  dplyr::filter(fil == TRUE) |> 
  ggplot(aes(x = CenterX_global_px, y = CenterY_global_px, color = typ)) +
  geom_point(size = 0.15, stroke = 0) + 
  coord_equal() +
  guides(colour = guide_legend(override.aes = list(size=4))) +
  scale_color_manual(values = typCols)
```

```{r}
#| fig-width: 12
#| fig-height: 5
cbind(spatialCoords(spe), colData(spe)) |>
  as.data.frame() |> 
  dplyr::filter(fil == TRUE) |> 
  ggplot(aes(y = -CenterX_global_px, x = CenterY_global_px, color = lv1)) +
  geom_point(size = 0.25, stroke = 0) + 
  coord_equal() +
  scale_color_manual(values = .pal_sub) +
  guides(colour = guide_legend(override.aes = list(size=4))) +
  theme_void()
```


# Structures per ROI

```{r}
spe$typ |> unique()
```


```{r}
#| eval: false

int <- shapeIntensityImage(
  spe[,!is.na(spe$typ)],
  marks = "lv1",
  imageCol = "typ",
  imageId = c("110_TVA1"),
  markSelect = "epi"
)
```


```{r}
params <- estimateReconstructionParametersSPE(
    spe,
    marks = "lv1",
    imageCol = "typ",
    markSelect = "epi",
    plotHist = TRUE,
    dim = 750
)
```


```{r}
mean(params$thres)
mean(params$bndw)
```

```{r}
idx <- spatialCoords(spe)[,1] < 60000 & 
  spatialCoords(spe)[,1] > 45000 & 
  spatialCoords(spe)[,2] < 60000 & 
  spatialCoords(spe)[,2] > 45000
```


```{r}
resSub <- reconstructShapeDensitySPE(
    spe[,idx],
    marks = "lv1",
    imageCol = "foo",
    markSelect = "epi",
    bndw = 60,
    thres = 8.5E-5,
    dim = 500
)
```


```{r}
cs1 <- grDevices::colorRampPalette(pals::alphabet(26))(dim(resSub)[1])

resSub |>
    mutate(struct = (cs1)) |>
    ggplot() +
    geom_sf(aes(fill = struct, color = struct)) +
    guides(color = "none", fill = "none") +
    scale_color_manual(values = cs1) +
    scale_fill_manual(values = cs1) +
    theme_void()
```


```{r}
#| column: screen
#| out-width: 100%
#| fig-width: 6
#| fig-heigth: 6

spe[,idx] |>
  (\(x) x[, colData(x)$fov %in% ls])() |>
  (\(x) cbind(spatialCoords(x), colData(x)))() |>
  as.data.frame() |>
  filter(!is.na(lv1)) |> 
  ggplot(aes(x = CenterX_global_px, y = CenterY_global_px, color = lv1)) +
  geom_point(size = 0.5, stroke = 0) +
  coord_equal() +
  guides(colour = guide_legend(override.aes = list(size = 3))) +
  geom_sf(
    data = resSub,
    fill = NA,
    color = "black",
    inherit.aes = FALSE,
    # this is important
    linewidth = 0.25
  ) +
  scale_color_manual(values = .pal_sub) +
  theme_void()
```
# All structs

```{r}
structs <- reconstructShapeDensitySPE(
    spe,
    marks = "lv1",
    imageCol = "foo",
    markSelect = "epi",
    bndw = 50,
    thres = 9E-5,
    dim = 2500
)
```


```{r}
#| fig-width: 15
#| fig-height: 35
cs1 <- sample(unname(pals::alphabet(26)), dim(structs)[1], replace = TRUE)

structs |>
    mutate(struct = (cs1)) |>
    ggplot() +
    geom_sf(aes(fill = struct, color = struct)) +
    guides(color = "none", fill = "none") +
    scale_color_manual(values = cs1) +
    scale_fill_manual(values = cs1) +
    theme_void()
```

## Assign cells to strucutres

```{r}
library("parallel")
df <- .SPE2df(spe, "foo", colNames = TRUE)
#ls <- split(df, as.factor(df[, imageCol]))

blocks <- split(df, ceiling(seq_len(nrow(df)) / 10000))


res <- mclapply(blocks, function(dfSel) {
    structsSel <- structs
    spatialCoordsSf <- st_as_sf(dfSel[, c(1, 2)], coords = c(colnames(dfSel)[1], 
        colnames(dfSel)[2]))
    n <- st_intersects(spatialCoordsSf, structsSel, sparse = FALSE)
    n_list <- apply(n, 1, function(x) which(x == TRUE)[1])
    res <- ifelse(n_list == 0, NA, structsSel[["structID"]][n_list])
    return(data.frame(colnamesSPE = dfSel$colnamesSPE, structAssign = res))
}, mc.cores = 5)

rd <- do.call("rbind", res)
out <- rd$structAssign
names(out) <- rd$colnamesSPE
```


```{r}
colData(spe)$structAssign <- out[colnames(spe)]
```

```{r}
#| fig-width: 15
#| fig-height: 25
cbind(spatialCoords(spe), colData(spe)) |>
  as.data.frame() |> 
  dplyr::filter(fil == TRUE & fov %in% ls) |> 
  #dplyr::filter(!is.na(structAssign)) |> 
  dplyr::filter(lv1 == "epi") |>
  ggplot(aes(x = CenterX_global_px, y = CenterY_global_px, color = structAssign)) +
  geom_point(size = 1, stroke = 0) + 
  coord_equal() +
  scale_color_manual(values = c(cs1)) +
  guides(colour = "none") +
    geom_sf(
    data = resSub,
    fill = NA,
    color = "navy",
    inherit.aes = FALSE,
    # this is important
    linewidth = 0.75
  )
```

# Struct metrics

```{r}
shapeMetrics <- totalShapeMetrics(structs)
shapeMetricsSub <- totalShapeMetrics(resSub)
```


```{r}
#| fig-width: 6
#| fig-heigth: 6
cbind(resSub, t(shapeMetricsSub)) |>
    ggplot() +
    geom_sf(aes(fill = fibreWidth, color = fibreWidth)) +
  scale_color_viridis_c(option = "A") +
  scale_fill_viridis_c(option = "A") +
  theme_void()
```

# Filter structs

```{r}
(fq <- quantile(shapeMetrics["Area",], c(0.4)))
```

```{r}
#| fig-width: 15
#| fig-height: 35
cbind(resSub, t(shapeMetricsSub)) |>
  filter(Area > fq[1]) |> 
    ggplot() +
    geom_sf(aes(fill = Area, color = Area)) +
  scale_color_viridis_c(option = "C") +
  scale_fill_viridis_c(option = "C")
```

```{r}
filts <- names(which(shapeMetrics["Area", ] > fq[1]))
spe$structAssignFilt <- ifelse(spe$structAssign %in% filts, spe$structAssign, NA)
```

```{r}
#| fig-width: 15
#| fig-height: 20
cs1 <- sample(unname(pals::alphabet(26)), dim(structs)[1], replace = TRUE)


cbind(spatialCoords(spe), colData(spe)) |>
  as.data.frame() |> 
  dplyr::filter(fil == TRUE & fov %in% ls) |> 
  #dplyr::filter(!is.na(structAssign)) |> 
  dplyr::filter(lv1 == "epi") |>
  ggplot(aes(x = CenterX_global_px, y = CenterY_global_px, color = structAssignFilt)) +
  geom_point(size = 1, stroke = 0) + 
  coord_equal() +
  scale_color_manual(values = c(cs1)) +
  guides(colour = "none") +
    geom_sf(
    data = resSub,
    fill = NA,
    color = "navy",
    inherit.aes = FALSE,
    # this is important
    linewidth = 0.75
  )
```
# Metrics

```{r}
# Specific color mapping - source: https://github.com/HelenaLC/WTx-TVA/blob/d75d0cd20a9880f11c1368e37ba39660e3f2e82c/code/_utils.R#L4
sm <- shapeMetrics |> 
  t() |> 
  as.data.frame() |> 
  tibble::rownames_to_column("structAssign")

df <- colData(spe)[!is.na(spe$structAssignFilt),] |> 
  as.data.frame() |> 
  left_join(sm, by = "structAssign" )
```

```{r}
colData(spe) |> 
  as.data.frame() |> 
  filter(lv1 == "epi") |> 
  select(lv2) |>
  pull() |> 
  unique() |> 
  as.character() -> namesLv2

lv2Cols <- pals::trubetskoy(length(namesLv2))
names(lv2Cols) <- sort(namesLv2)
```


```{r}
#| fig-width: 8
#| fig-heigth: 8
df |> 
  filter(lv1 == "epi") |> 
  ggplot(aes(x = reorder(lv2, fibreWidth), y = fibreWidth, fill = lv2)) +
  geom_boxplot(alpha = 0.85) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(fill = "") +
  scale_fill_manual(values = lv2Cols)
  #labs(title = "Fibre width per cell in different epi cell types")
```

```{r}
#| fig-width: 5
#| fig-height: 5
df |> 
  filter(!is.na(typ)) |> 
  filter(lv1 == "epi") |> 
  filter(!is.na(structAssignFilt)) |> 
  ggplot(aes(x = reorder(typ, fibreWidth), y = fibreWidth, fill = typ)) +
  geom_boxplot(alpha = 0.85) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(fill = "") +
  scale_fill_manual(values = typCols) 
  #labs(title = "Fibre width per cell in different regions")
```
```{r}
# custom order
.fw <- facet_wrap(~factor(typ, c("110_REF", "110_TVA1", "110_TVA2",
                                 "110_TVA3", "110_CRC")))

```

```{r}
df |> 
  filter(lv1 == "epi") |> 
  ggplot(aes(x = trj, y = fibreWidth, color = typ)) +
  geom_point() +
  labs(color = "") +
  scale_color_manual(values = typCols) +
  .fw
```


```{r}
#| fig-width: 5
#| fig-height: 5
df |> 
  filter(lv1 == "epi") |> 
  group_by(structAssign) |> 
  reframe(medianTrj = median(trj), medianFibreWitdh = median(fibreWidth), typ = typ) |> 
  ggplot(aes(x = medianFibreWitdh, y = medianTrj, color = typ)) +
  geom_point() +
  labs(color = "") +
  scale_color_manual(values = typCols) +
  #labs(title = "Median trajectory vs. mean fibre width per structure") +
  geom_smooth(method = "lm", color = "black")
```

```{r}
df |> 
  filter(lv1 == "epi") |> 
  group_by(structAssign) |> 
  reframe(medianTrj = median(trj), medianFibreWitdh = median(fibreWidth), typ = typ) -> seltr


cor.test(seltr$medianTrj, seltr$medianFibreWitdh)
```


```{r}
df |> 
  filter(lv1 == "epi") |> 
  group_by(structAssign) |> 
  reframe(medianPanCK = median(Mean.PanCK), medianFibreWitdh = median(fibreWidth), typ = typ) |> 
  ggplot(aes(x = medianFibreWitdh, y = asinh(medianPanCK/200), color = typ)) +
  geom_point() +
  labs(color = "") +
  scale_color_manual(values = typCols) +
  labs(title = "Median panCK vs. mean fibre width per structure") +
  geom_smooth(method = "lm", color = "black")
```

# Proportions

```{r}
propsTyp <- cellTypeProportions(spe[, !is.na(spe$typ)], "structAssignFilt", "typ", nCores = 4)
```


```{r}
propsTyp %>%
  filter(if_any(everything(), ~ . < 0.99 & . > 0.01)) -> propsel
```


```{r}
propsel |> 
  tibble::rownames_to_column("structAssign") |>
  left_join(sm, by = "structAssign") |> 
  arrange(desc(Area))
```


```{r}
spe$trans <- "no"
spe$trans[spe$structAssignFilt %in% rownames(propsel)] <- "yes"
```


```{r}
#| fig-width: 15
#| fig-height: 35

trp <- "RT|RC|TT|TC|T2C"

cbind(spatialCoords(spe), colData(spe)) |>
  as.data.frame() |> 
  dplyr::filter(fil == TRUE) |> 
  mutate(transCrpyt = case_when(
    stringr::str_detect(roi, trp) & trans == "yes" ~ "both",
    stringr::str_detect(roi, trp) ~ "original_annotation",
    trans == "yes" ~ "sosta_only",
    TRUE ~ NA_character_)) |> 
  ggplot(aes(x = CenterX_global_px, y = CenterY_global_px, color = transCrpyt)) +
  geom_point(size = 0.5, stroke = 0) + 
  coord_equal() +
  guides(colour = guide_legend(override.aes = list(size=5))) +
  scale_color_manual(values = c("darkred", "gold", "navy"))
```

```{r}
#| fig-width: 15
#| fig-height: 35
cbind(spatialCoords(spe), colData(spe)) |>
  as.data.frame() |> 
  dplyr::filter(fil == TRUE) |> 
  ggplot(aes(x = CenterX_global_px, y = CenterY_global_px, color = trans)) +
  geom_point(size = 0.5, stroke = 0) + 
  coord_equal() +
  scale_color_manual(values = c("steelblue", "darkred")) +
  guides(colour = guide_legend(override.aes = list(size=3)))
```
```{r}
#| fig-width: 15
#| fig-height: 35
cbind(spatialCoords(spe), colData(spe)) |>
  as.data.frame() |> 
  dplyr::filter(fil == TRUE) |> 
  ggplot(aes(x = CenterX_global_px, y = CenterY_global_px, color = roi)) +
  geom_point(size = 0.5, stroke = 0) + 
  coord_equal() +
  guides(colour = guide_legend(override.aes = list(size=3)))
```

# Proportion of cell types

```{r}
propsLv1 <- cellTypeProportions(spe[, !is.na(spe$typ)], "structAssign", "lv2", nCores = 4)
```

```{r}
ncl <- colData(spe) |> 
  as.data.frame() |> 
  filter(!is.na(structAssignFilt)) |> 
  group_by(structAssign) |> 
  summarise(ncells = n())
```


```{r}
propsLv1 %>%
  filter(if_any(everything(), ~ . < 0.99 & . > 0.01)) -> psl
```


```{r}
psl |> 
  tibble::rownames_to_column("structAssign") |>
  left_join(sm, by = "structAssign") |> 
  arrange(desc(Area)) |> 
  left_join(ncl, by = "structAssign") -> psl
```

```{r}
psl |>
  mutate(epi.ref = rowSums(across(
    c(
      epi.EE,
      epi.entero,
      epi.goblet
    )
  ))) |>
  mutate(epi.pat = rowSums(across(
    c(`epi.goblet-like_REG4`,
      `epi.entero-like_ACSF2`,
      `epi.entero-like_EREG`,      
      `epi.fetal-like_EMP1`,
      `epi.fetal-like_MMP7`,
      epi.inflam_REG1A,
      `epi.paneth-like_DEFA6`,
      epi.prolif,
      epi.prolif_H1,
      epi.prolif_STMN1,
      epi.prolif_TACC3,
      `epi.stem-like_CLU`,
      `epi.stem-like_CLU`
    )
  ))) |>
  mutate(epi.tot = epi.ref + epi.pat) |>
  mutate(epi.ref.norm = epi.ref / (epi.ref + epi.pat)) |>
  mutate(epi.pat.norm = epi.pat / (epi.ref + epi.pat)) -> psl
```

```{r}
colData(spe) |>
  as.data.frame() |> 
  filter(!is.na(roi)) |> 
  unique() |> 
  pull(structAssign) -> annot


psl |> 
  filter(structAssign %in% annot) |> 
  select(epi.ref:epi.pat.norm)
```


```{r}
psl |> 
  filter(epi.tot > 0.5 & epi.ref.norm > 0.001  & epi.pat > 0.5 &
           ncells > 30 & ncells < 1000) |> 
  pull(structAssign) -> stsel
```

```{r}
length(stsel)

colData(spe) |>
  as.data.frame() |> 
  filter(structAssign %in% stsel & !is.na(roi)) |> 
  group_by(roi) |> 
  summarize(n = n())
```


```{r}
#| fig-width: 15
#| fig-height: 35
cbind(spatialCoords(spe), colData(spe)) |>
  as.data.frame() |> 
  dplyr::filter(structAssign %in% stsel) |> 
  ggplot(aes(x = CenterX_global_px, y = CenterY_global_px, color = roi)) +
  geom_point(size = 0.5, stroke = 0) + 
  coord_equal() +
  guides(colour = guide_legend(override.aes = list(size=3)))
```

# Aggregate across structures

```{r}
  epi_gen <- list(
  "epi.EE" = c("PYY", "SST", "CHGA", "CHGB", "NEUROD1", "GCG", "INSL5"),
  "epi.goblet" = c(
  "BEST2",
  "MUC2",
  "MUC4",
  "TFF3",
  "FCGBP",
  "ZG16",
  "ATOH1",
  "KLK1",
  "CLCA1",
  "ITLN1"
  ),
  "epi.goblet-like_REG4" = c("MUC5AC", "REG4", "GRIP2", "RETNLB", "SYTL1", "PLXND1"),
  "epi.inflam_REG1A" = c(
  "SAA1",
  "OLFM4",
  "DMBT1",
  "S100A9",
  "HLA-DRA",
  "HLA-DPA1",
  "CXCL1",
  "CXCL2",
  "CXCL3"
  ),
  "epi.paneth-like_DEFA6" = c("REG1A", "REG1B", "REG3A", "DEFA5", "DEFA6", "DLL1", "ITLN2"),
  "epi.entero" = c(
  "FABP1",
  "CA1",
  "CA2",
  "CA4",
  "GUCA2A",
  "MS4A12",
  "CEACAM7",
  "SLC26A3"
  ),
  "epi.entero-like_ACSF2" = c(
  "TTLL3",
  "PIGZ",
  "CCDC183",
  "SELENBP1",
  "ACSF2",
  "SHROOM1",
  "EXD3"
  ),
  "epi.entero-like_EREG" = c(
  "EREG",
  "ANO9",
  "NCOA7",
  "TNNC2",
  "ARID3A",
  "FITM2",
  "UCKL1",
  "SRPX2",
  "SPAG4",
  "THBS1",
  "HBEGF"
  ),
  "epi.stem-like_LGR5" = c(
  "LGR5",
  "FN1",
  "STRAP",
  "CDX2",
  "TGFBI",
  "CEL",
  "SMOC2",
  "ASCL2",
  "RNF43",
  "RGMB"
  ),
  "epi.stem-like_CLU" = c("LEFTY1", "CLU", "PTGDR", "CD44", "SAMD5", "KIF13A", "TRPM5"),
  "epi.fetal-like_MMP7" = c(
  "NOTUM",
  "KRT23",
  "UBD",
  "FLNA",
  "FSTL3",
  "CAVIN1",
  "BST2",
  "KLK6",
  "KLK10",
  "AKAP12",
  "TIMP2",
  "PPL",
  "S100A4",
  "SDC4",
  "MMP7",
  "LAMA3",
  "LAMB3",
  "LAMC2",
  "PLAUR",
  "SLC2A1",
  "TNFAIP2",
  "RHOF"
  ),
  "epi.fetal-like_EMP1" = c(
  "CXCL8",
  "MSLN",
  "DUSP5",
  "TM4SF1",
  "EMP1",
  "MUC17",
  "ANXA1",
  "DUOX2",
  "DUOXA2",
  "CD55",
  "ERO1A",
  "ECM1",
  "ENO2",
  "PFKFB3",
  "EGLN3",
  "SERPINE2",
  "ERRFI1",
  "CTSE",
  "COL17A1"
  ),
  "epi.prolif_TACC3" = c(
  "MKI67",
  "TOP2A",
  "MYO19",
  "NCAPG2",
  "IQGAP3",
  "FANCA",
  "RAD54L",
  "TROAP",
  "TACC3",
  "STMN1",
  "SUMO3",
  "TUBA1B",
  "TUBB4B",
  "H2AC4",
  "H1-3",
  "H1-5",
  "H3C7",
  "H2BC15",
  "CDK1",
  "RARRES1"
  ),
  "epi.prolif_STMN1" = c(),
  "epi.prolif_H1" = c(),
  "epi.prolif" = c()
  )
```


## Bulk 

```{r}
out <- aggregateAcrossCells(spe, spe$structAssign,
                     statistics = "mean",
                     BPPARAM = bpparam)
```

```{r}
aggMet <- t(shapeMetrics) |> 
  as.data.frame() |> 
  tibble::rownames_to_column("ids") |> 
  rename(structArea = Area ) |> 
  right_join(as.data.frame(colData(out)), by = "ids") |> 
  tibble::column_to_rownames("ids")
```

## Prop detectedd

```{r}
feats <- c("structArea", "Compactness", "Eccentricity", "Circularity",
                 "Solidity", "Curl", "fibreLength", "fibreWidth")

```


```{r}
geneCors <- computeCorrelations(log1p(counts(out)),
                    t(as.matrix(aggMet[out$ids, feats])),
                    BPPARAM = bpparam
                    )
```

```{r}
gene_corrs <- geneCors[!is.na(geneCors$FDR),]
gene_corrs <- gene_corrs[gene_corrs$FDR < 0.1,]
gene_corrs <- gene_corrs[order(gene_corrs$rho, decreasing = TRUE),]
```

```{r}
sel.correlcation <- gene_corrs[gene_corrs$feature2 %in% c("fibreWidth"),]

sel.correlcation |>
  as.data.frame() |> 
  arrange(desc(rho)) |> 
  filter(feature1 %in% unlist(epi_gen)) |> 
  filter(FDR < 0.05) |> 
  head(n = 10)
  
sel.correlcation |>
  as.data.frame() |> 
  arrange(desc(rho)) |> 
  #filter(feature1 %in% unlist(epi_gen)) |> 
  filter(FDR < 0.05) |> 
  tail(n = 10)
```
```{r}
which(rowSums(counts(out) > 1) / ncol(counts(out)) > 0.025) |> 
  names() -> filtG
```


```{r}
#| fig-width: 5
#| fig-height: 10
library(ComplexHeatmap)
  
geneCors |> 
  as.data.frame() |> 
  filter(feature1 %in% unlist(epi_gen)) |> 
  filter(feature1 %in% filtG) |> 
  filter(feature2 == "fibreWidth") |> 
  select(feature1, feature2, rho) |> 
  pivot_wider(names_from = feature2, values_from = rho) |> 
  tibble::column_to_rownames("feature1") |> 
  as.matrix() -> heatmat


gene_order <- unlist(epi_gen)
gene_category <- rep(names(epi_gen), lengths(epi_gen))
names(gene_category) <- gene_order

ordered_rows <- intersect(gene_order, rownames(heatmat))

category_names <- unique(gene_category[ordered_rows])
category_colors <- setNames(pals::alphabet2(length(category_names)), category_names)
  
ha_row <- rowAnnotation(
  Category = gene_category[ordered_rows],
  col = list(Category = category_colors)
)
```


```{r}
Heatmap(
  heatmat,
  name = "rho",
  cluster_rows = TRUE,
  cluster_columns = TRUE,
  show_row_names = TRUE,  
  show_column_names = TRUE,
  left_annotation = ha_row
)

```


```{r}
#| fig-width: 15
#| fig-height: 35
plotCoords(spe,
          annotate = "PLAUR",
          in_tissue = NULL,
          y_reverse = FALSE)
```

```{r}
plot(shapeMetrics["fibreWidth", colnames(counts(out))], 
log1p(counts(out)["MUC2",]))
```


# SessionInfo

```{r}
sessionInfo()
```

